//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.27.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using System.Collections.Generic;

namespace PCApplication.JsonSchemas {
    public class LogsResponse {
        [Newtonsoft.Json.JsonProperty("information", Required = Newtonsoft.Json.Required.Always)]
        public List<Information> Information { get; set; }
    }

    public class Information {
        [Newtonsoft.Json.JsonProperty("no", Required = Newtonsoft.Json.Required.Always)]
        public int No { get; set; }

        [Newtonsoft.Json.JsonProperty("severite", Required = Newtonsoft.Json.Required.Always)]
        public string Severite { get; set; }

        [Newtonsoft.Json.JsonProperty("heure", Required = Newtonsoft.Json.Required.Always)]
        public string Heure { get; set; }

        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Always)]
        public string Message { get; set; }
    }
}
